# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nodes.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class DependsOn(betterproto.Message):
    macros: List[str] = betterproto.string_field(1)
    nodes: List[str] = betterproto.string_field(2)


@dataclass
class ModelNode(betterproto.Message):
    resource_type: str = betterproto.string_field(1)
    unique_id: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    package_name: str = betterproto.string_field(4)
    alias: str = betterproto.string_field(5)
    depends_on: "DependsOn" = betterproto.message_field(6)
    database: str = betterproto.string_field(7)
    schema: str = betterproto.string_field(8)
    language: str = betterproto.string_field(9)
    original_file_path: str = betterproto.string_field(10)
    tags: List[str] = betterproto.string_field(11)
    description: str = betterproto.string_field(12)
