# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List

import betterproto


@dataclass
class TimingInfoMsg(betterproto.Message):
    """TimingInfo"""

    name: str = betterproto.string_field(1)
    started_at: datetime = betterproto.message_field(2)
    completed_at: datetime = betterproto.message_field(3)


@dataclass
class NodeInfo(betterproto.Message):
    """NodeInfo"""

    node_path: str = betterproto.string_field(1)
    node_name: str = betterproto.string_field(2)
    unique_id: str = betterproto.string_field(3)
    resource_type: str = betterproto.string_field(4)
    materialized: str = betterproto.string_field(5)
    node_status: str = betterproto.string_field(6)
    node_started_at: str = betterproto.string_field(7)
    node_finished_at: str = betterproto.string_field(8)


@dataclass
class RunResultMsg(betterproto.Message):
    """RunResult"""

    status: str = betterproto.string_field(1)
    message: str = betterproto.string_field(2)
    timing_info: List["TimingInfoMsg"] = betterproto.message_field(3)
    thread: str = betterproto.string_field(4)
    execution_time: float = betterproto.float_field(5)
    adapter_response: Dict[str, str] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    num_failures: int = betterproto.int32_field(7)


@dataclass
class ReferenceKeyMsg(betterproto.Message):
    """ReferenceKey"""

    database: str = betterproto.string_field(1)
    schema: str = betterproto.string_field(2)
    identifier: str = betterproto.string_field(3)


@dataclass
class ListOfStrings(betterproto.Message):
    """ListOfStrings"""

    value: List[str] = betterproto.string_field(1)


@dataclass
class MainReportVersion(betterproto.Message):
    """A001 - 101"""

    version: str = betterproto.string_field(1)
    log_version: int = betterproto.int32_field(2)


@dataclass
class MainReportArgs(betterproto.Message):
    """A002 - 102"""

    args: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class MainTrackingUserState(betterproto.Message):
    """A003 - 103"""

    user_state: str = betterproto.string_field(1)


@dataclass
class MergedFromState(betterproto.Message):
    """A004 - 104"""

    num_merged: int = betterproto.int32_field(1)
    sample: List[str] = betterproto.string_field(2)


@dataclass
class MissingProfileTarget(betterproto.Message):
    """A005 - 105"""

    profile_name: str = betterproto.string_field(1)
    target_name: str = betterproto.string_field(2)


@dataclass
class InvalidVarsYAML(betterproto.Message):
    """A008 - 108"""

    pass


@dataclass
class DbtProjectError(betterproto.Message):
    """A009 - 109"""

    pass


@dataclass
class DbtProjectErrorException(betterproto.Message):
    """A010 - 110"""

    exc: str = betterproto.string_field(1)


@dataclass
class DbtProfileError(betterproto.Message):
    """A011 - 111"""

    pass


@dataclass
class DbtProfileErrorException(betterproto.Message):
    """A012 - 112"""

    exc: str = betterproto.string_field(1)


@dataclass
class ProfileListTitle(betterproto.Message):
    """A013 - 113"""

    pass


@dataclass
class ListSingleProfile(betterproto.Message):
    """A014 - 114"""

    profile: str = betterproto.string_field(1)


@dataclass
class NoDefinedProfiles(betterproto.Message):
    """A015 - 115"""

    pass


@dataclass
class ProfileHelpMessage(betterproto.Message):
    """A016 - 116"""

    pass


@dataclass
class StarterProjectPath(betterproto.Message):
    """A017 - 117"""

    dir: str = betterproto.string_field(1)


@dataclass
class ConfigFolderDirectory(betterproto.Message):
    """A018 - 118"""

    dir: str = betterproto.string_field(1)


@dataclass
class NoSampleProfileFound(betterproto.Message):
    """A019 - 119"""

    adapter: str = betterproto.string_field(1)


@dataclass
class ProfileWrittenWithSample(betterproto.Message):
    """A020 - 120"""

    name: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class ProfileWrittenWithTargetTemplateYAML(betterproto.Message):
    """A021 - 121"""

    name: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class ProfileWrittenWithProjectTemplateYAML(betterproto.Message):
    """A022 - 122"""

    name: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class SettingUpProfile(betterproto.Message):
    """A023 - 123"""

    pass


@dataclass
class InvalidProfileTemplateYAML(betterproto.Message):
    """A024 - 124"""

    pass


@dataclass
class ProjectNameAlreadyExists(betterproto.Message):
    """A025 - 125"""

    name: str = betterproto.string_field(1)


@dataclass
class ProjectCreated(betterproto.Message):
    """A026 - 126"""

    project_name: str = betterproto.string_field(1)
    docs_url: str = betterproto.string_field(2)
    slack_url: str = betterproto.string_field(3)


@dataclass
class PackageRedirectDeprecation(betterproto.Message):
    """D001 - 201"""

    old_name: str = betterproto.string_field(1)
    new_name: str = betterproto.string_field(2)


@dataclass
class PackageInstallPathDeprecation(betterproto.Message):
    """D002 - 202"""

    pass


@dataclass
class ConfigSourcePathDeprecation(betterproto.Message):
    """D003 - 203"""

    deprecated_path: str = betterproto.string_field(1)
    exp_path: str = betterproto.string_field(2)


@dataclass
class ConfigDataPathDeprecation(betterproto.Message):
    """D004 - 204"""

    deprecated_path: str = betterproto.string_field(1)
    exp_path: str = betterproto.string_field(2)


@dataclass
class AdapterDeprecationWarning(betterproto.Message):
    """D005 - 205"""

    old_name: str = betterproto.string_field(1)
    new_name: str = betterproto.string_field(2)


@dataclass
class MetricAttributesRenamed(betterproto.Message):
    """D006 - 206"""

    metric_name: str = betterproto.string_field(1)


@dataclass
class ExposureNameDeprecation(betterproto.Message):
    """D007 - 207"""

    exposure: str = betterproto.string_field(1)


@dataclass
class AdapterEventDebug(betterproto.Message):
    """E001 - 301"""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: List[str] = betterproto.string_field(3)


@dataclass
class AdapterEventInfo(betterproto.Message):
    """E002 - 302"""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: List[str] = betterproto.string_field(3)


@dataclass
class AdapterEventWarning(betterproto.Message):
    """E003 - 303"""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: List[str] = betterproto.string_field(3)


@dataclass
class AdapterEventError(betterproto.Message):
    """E004 - 304"""

    name: str = betterproto.string_field(1)
    base_msg: str = betterproto.string_field(2)
    args: List[str] = betterproto.string_field(3)
    exc_info: str = betterproto.string_field(4)


@dataclass
class NewConnection(betterproto.Message):
    """E005 - 305"""

    conn_type: str = betterproto.string_field(1)
    conn_name: str = betterproto.string_field(2)


@dataclass
class ConnectionReused(betterproto.Message):
    """E006 - 306"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class ConnectionLeftOpenInCleanup(betterproto.Message):
    """E007 - 307"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class ConnectionClosedInCleanup(betterproto.Message):
    """E008 - 308"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class RollbackFailed(betterproto.Message):
    """E009 - 309"""

    conn_name: str = betterproto.string_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class ConnectionClosed(betterproto.Message):
    """E010 - 310"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class ConnectionLeftOpen(betterproto.Message):
    """E011 - 311"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class Rollback(betterproto.Message):
    """E012 - 312"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class CacheMiss(betterproto.Message):
    """E013 -313"""

    conn_name: str = betterproto.string_field(1)
    database: str = betterproto.string_field(2)
    schema: str = betterproto.string_field(3)


@dataclass
class ListRelations(betterproto.Message):
    """E014 - 314"""

    database: str = betterproto.string_field(1)
    schema: str = betterproto.string_field(2)
    relations: List["ReferenceKeyMsg"] = betterproto.message_field(3)


@dataclass
class ConnectionUsed(betterproto.Message):
    """E015 - 315"""

    conn_type: str = betterproto.string_field(1)
    conn_name: str = betterproto.string_field(2)


@dataclass
class SQLQuery(betterproto.Message):
    """E016 - 316"""

    conn_name: str = betterproto.string_field(1)
    sql: str = betterproto.string_field(2)


@dataclass
class SQLQueryStatus(betterproto.Message):
    """E017 - 317"""

    status: str = betterproto.string_field(1)
    elapsed: float = betterproto.float_field(2)


@dataclass
class SQLCommit(betterproto.Message):
    """E018 - 318"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class ColTypeChange(betterproto.Message):
    """E019 - 319"""

    orig_type: str = betterproto.string_field(1)
    new_type: str = betterproto.string_field(2)
    table: "ReferenceKeyMsg" = betterproto.message_field(3)


@dataclass
class SchemaCreation(betterproto.Message):
    """E020 - 320"""

    relation: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class SchemaDrop(betterproto.Message):
    """E021 - 321"""

    relation: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class UncachedRelation(betterproto.Message):
    """E022 - 322"""

    dep_key: "ReferenceKeyMsg" = betterproto.message_field(1)
    ref_key: "ReferenceKeyMsg" = betterproto.message_field(2)


@dataclass
class AddLink(betterproto.Message):
    """E023 - 323"""

    dep_key: "ReferenceKeyMsg" = betterproto.message_field(1)
    ref_key: "ReferenceKeyMsg" = betterproto.message_field(2)


@dataclass
class AddRelation(betterproto.Message):
    """E024 - 324"""

    relation: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class DropMissingRelation(betterproto.Message):
    """E025 - 325"""

    relation: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class DropCascade(betterproto.Message):
    """E026 - 326"""

    dropped: "ReferenceKeyMsg" = betterproto.message_field(1)
    consequences: List["ReferenceKeyMsg"] = betterproto.message_field(2)


@dataclass
class DropRelation(betterproto.Message):
    """E027 - 327"""

    dropped: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class UpdateReference(betterproto.Message):
    """E028 - 328"""

    old_key: "ReferenceKeyMsg" = betterproto.message_field(1)
    new_key: "ReferenceKeyMsg" = betterproto.message_field(2)
    cached_key: "ReferenceKeyMsg" = betterproto.message_field(3)


@dataclass
class TemporaryRelation(betterproto.Message):
    """E029 - 329"""

    key: "ReferenceKeyMsg" = betterproto.message_field(1)


@dataclass
class RenameSchema(betterproto.Message):
    """E030 - 330"""

    old_key: "ReferenceKeyMsg" = betterproto.message_field(1)
    new_key: "ReferenceKeyMsg" = betterproto.message_field(2)


@dataclass
class DumpBeforeAddGraph(betterproto.Message):
    """E031 - 331"""

    dump: Dict[str, "ListOfStrings"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class DumpAfterAddGraph(betterproto.Message):
    """E032 - 332"""

    dump: Dict[str, "ListOfStrings"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class DumpBeforeRenameSchema(betterproto.Message):
    """E033 - 333"""

    dump: Dict[str, "ListOfStrings"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class DumpAfterRenameSchema(betterproto.Message):
    """E034 - 334"""

    dump: Dict[str, "ListOfStrings"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass
class AdapterImportError(betterproto.Message):
    """E035 - 335"""

    exc: str = betterproto.string_field(1)


@dataclass
class PluginLoadError(betterproto.Message):
    """E036 - 336"""

    exc_info: str = betterproto.string_field(1)


@dataclass
class NewConnectionOpening(betterproto.Message):
    """E037 - 337"""

    connection_state: str = betterproto.string_field(1)


@dataclass
class CodeExecution(betterproto.Message):
    """E038 - 338"""

    conn_name: str = betterproto.string_field(1)
    code_content: str = betterproto.string_field(2)


@dataclass
class CodeExecutionStatus(betterproto.Message):
    """E039 - 339"""

    status: str = betterproto.string_field(1)
    elapsed: float = betterproto.float_field(2)


@dataclass
class CatalogGenerationError(betterproto.Message):
    """E040 - 340"""

    exc: str = betterproto.string_field(1)


@dataclass
class WriteCatalogFailure(betterproto.Message):
    """E041 - 341"""

    num_exceptions: int = betterproto.int32_field(1)


@dataclass
class CatalogWritten(betterproto.Message):
    """E042 - 342"""

    path: str = betterproto.string_field(1)


@dataclass
class CannotGenerateDocs(betterproto.Message):
    """E043 - 343"""

    pass


@dataclass
class BuildingCatalog(betterproto.Message):
    """E044 - 344"""

    pass


@dataclass
class DatabaseErrorRunningHook(betterproto.Message):
    """E045 - 345"""

    hook_type: str = betterproto.string_field(1)


@dataclass
class HooksRunning(betterproto.Message):
    """E046 - 346"""

    num_hooks: int = betterproto.int32_field(1)
    hook_type: str = betterproto.string_field(2)


@dataclass
class HookFinished(betterproto.Message):
    """E047 - 347"""

    stat_line: str = betterproto.string_field(1)
    execution: str = betterproto.string_field(2)
    execution_time: float = betterproto.float_field(3)


@dataclass
class ParseCmdStart(betterproto.Message):
    """I001 - 401"""

    pass


@dataclass
class ParseCmdCompiling(betterproto.Message):
    """I002 - 402"""

    pass


@dataclass
class ParseCmdWritingManifest(betterproto.Message):
    """I003 - 403"""

    pass


@dataclass
class ParseCmdDone(betterproto.Message):
    """I004 - 404"""

    pass


@dataclass
class ManifestDependenciesLoaded(betterproto.Message):
    """I005 - 405"""

    pass


@dataclass
class ManifestLoaderCreated(betterproto.Message):
    """I006 - 406"""

    pass


@dataclass
class ManifestLoaded(betterproto.Message):
    """I007 - 407"""

    pass


@dataclass
class ManifestChecked(betterproto.Message):
    """I008 - 408"""

    pass


@dataclass
class ManifestFlatGraphBuilt(betterproto.Message):
    """I009 - 409"""

    pass


@dataclass
class ParseCmdPerfInfoPath(betterproto.Message):
    """I010 - 410"""

    path: str = betterproto.string_field(1)


@dataclass
class GenericTestFileParse(betterproto.Message):
    """I011 - 411"""

    path: str = betterproto.string_field(1)


@dataclass
class MacroFileParse(betterproto.Message):
    """I012 - 412"""

    path: str = betterproto.string_field(1)


@dataclass
class PartialParsingFullReparseBecauseOfError(betterproto.Message):
    """I013 - 413"""

    pass


@dataclass
class PartialParsingExceptionFile(betterproto.Message):
    """I014 - 414"""

    file: str = betterproto.string_field(1)


@dataclass
class PartialParsingFile(betterproto.Message):
    """I015 - 415"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingException(betterproto.Message):
    """I016 - 416"""

    exc_info: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class PartialParsingSkipParsing(betterproto.Message):
    """I017 - 417"""

    pass


@dataclass
class PartialParsingMacroChangeStartFullParse(betterproto.Message):
    """I018 - 418"""

    pass


@dataclass
class PartialParsingProjectEnvVarsChanged(betterproto.Message):
    """I019 - 419"""

    pass


@dataclass
class PartialParsingProfileEnvVarsChanged(betterproto.Message):
    """I020 - 420"""

    pass


@dataclass
class PartialParsingDeletedMetric(betterproto.Message):
    """I021 - 421"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class ManifestWrongMetadataVersion(betterproto.Message):
    """I022 - 422"""

    version: str = betterproto.string_field(1)


@dataclass
class PartialParsingVersionMismatch(betterproto.Message):
    """I023 - 423"""

    saved_version: str = betterproto.string_field(1)
    current_version: str = betterproto.string_field(2)


@dataclass
class PartialParsingFailedBecauseConfigChange(betterproto.Message):
    """I024 - 424"""

    pass


@dataclass
class PartialParsingFailedBecauseProfileChange(betterproto.Message):
    """I025 - 425"""

    pass


@dataclass
class PartialParsingFailedBecauseNewProjectDependency(betterproto.Message):
    """I026 - 426"""

    pass


@dataclass
class PartialParsingFailedBecauseHashChanged(betterproto.Message):
    """I027 - 427"""

    pass


@dataclass
class PartialParsingNotEnabled(betterproto.Message):
    """I028 - 428"""

    pass


@dataclass
class ParsedFileLoadFailed(betterproto.Message):
    """I029 - 429"""

    path: str = betterproto.string_field(1)
    exc: str = betterproto.string_field(2)
    exc_info: str = betterproto.string_field(3)


@dataclass
class PartialParseSaveFileNotFound(betterproto.Message):
    """I030 - 430"""

    pass


@dataclass
class StaticParserCausedJinjaRendering(betterproto.Message):
    """I031 - 431"""

    path: str = betterproto.string_field(1)


@dataclass
class UsingExperimentalParser(betterproto.Message):
    """I032 - 432"""

    path: str = betterproto.string_field(1)


@dataclass
class SampleFullJinjaRendering(betterproto.Message):
    """I033 - 433"""

    path: str = betterproto.string_field(1)


@dataclass
class StaticParserFallbackJinjaRendering(betterproto.Message):
    """I034 - 434"""

    path: str = betterproto.string_field(1)


@dataclass
class StaticParsingMacroOverrideDetected(betterproto.Message):
    """I035 - 435"""

    path: str = betterproto.string_field(1)


@dataclass
class StaticParserSuccess(betterproto.Message):
    """I036 - 436"""

    path: str = betterproto.string_field(1)


@dataclass
class StaticParserFailure(betterproto.Message):
    """I037 - 437"""

    path: str = betterproto.string_field(1)


@dataclass
class ExperimentalParserSuccess(betterproto.Message):
    """I038 - 438"""

    path: str = betterproto.string_field(1)


@dataclass
class ExperimentalParserFailure(betterproto.Message):
    """I039 - 439"""

    path: str = betterproto.string_field(1)


@dataclass
class PartialParsingEnabled(betterproto.Message):
    """I040 - 440"""

    deleted: int = betterproto.int32_field(1)
    added: int = betterproto.int32_field(2)
    changed: int = betterproto.int32_field(3)


@dataclass
class PartialParsingAddedFile(betterproto.Message):
    """I041 - 441"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingDeletedFile(betterproto.Message):
    """I042 - 442"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingUpdatedFile(betterproto.Message):
    """I043 - 443"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingNodeMissingInSourceFile(betterproto.Message):
    """I044 - 444"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingMissingNodes(betterproto.Message):
    """I045 - 445"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingChildMapMissingUniqueID(betterproto.Message):
    """I046 - 446"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingUpdateSchemaFile(betterproto.Message):
    """I047 - 447"""

    file_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingDeletedSource(betterproto.Message):
    """I048 - 448"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class PartialParsingDeletedExposure(betterproto.Message):
    """I049 - 449"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class InvalidDisabledTargetInTestNode(betterproto.Message):
    """I050 - 450"""

    resource_type_title: str = betterproto.string_field(1)
    unique_id: str = betterproto.string_field(2)
    original_file_path: str = betterproto.string_field(3)
    target_kind: str = betterproto.string_field(4)
    target_name: str = betterproto.string_field(5)
    target_package: str = betterproto.string_field(6)


@dataclass
class UnusedResourceConfigPath(betterproto.Message):
    """I051 - 451"""

    unused_config_paths: List[str] = betterproto.string_field(1)


@dataclass
class SeedIncreased(betterproto.Message):
    """I052 - 452"""

    package_name: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class SeedExceedsLimitSamePath(betterproto.Message):
    """I053 - 453"""

    package_name: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class SeedExceedsLimitAndPathChanged(betterproto.Message):
    """I054 - 454"""

    package_name: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class SeedExceedsLimitChecksumChanged(betterproto.Message):
    """I055 - 455"""

    package_name: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    checksum_name: str = betterproto.string_field(3)


@dataclass
class UnusedTables(betterproto.Message):
    """I056 - 456"""

    unused_tables: List[str] = betterproto.string_field(1)


@dataclass
class WrongResourceSchemaFile(betterproto.Message):
    """I057 - 457"""

    patch_name: str = betterproto.string_field(1)
    resource_type: str = betterproto.string_field(2)
    plural_resource_type: str = betterproto.string_field(3)
    yaml_key: str = betterproto.string_field(4)
    file_path: str = betterproto.string_field(5)


@dataclass
class NoNodeForYamlKey(betterproto.Message):
    """I058 - 458"""

    patch_name: str = betterproto.string_field(1)
    yaml_key: str = betterproto.string_field(2)
    file_path: str = betterproto.string_field(3)


@dataclass
class MacroPatchNotFound(betterproto.Message):
    """I059 - 459"""

    patch_name: str = betterproto.string_field(3)


@dataclass
class NodeNotFoundOrDisabled(betterproto.Message):
    """I060 - 460"""

    original_file_path: str = betterproto.string_field(1)
    unique_id: str = betterproto.string_field(2)
    resource_type_title: str = betterproto.string_field(3)
    target_name: str = betterproto.string_field(4)
    target_kind: str = betterproto.string_field(5)
    target_package: str = betterproto.string_field(6)
    disabled: str = betterproto.string_field(7)


@dataclass
class GeneralMacroWarning(betterproto.Message):
    """I061 - 461"""

    msg: str = betterproto.string_field(1)


@dataclass
class GitSparseCheckoutSubdirectory(betterproto.Message):
    """M001 - 501"""

    subdir: str = betterproto.string_field(1)


@dataclass
class GitProgressCheckoutRevision(betterproto.Message):
    """M002 - 502"""

    revision: str = betterproto.string_field(1)


@dataclass
class GitProgressUpdatingExistingDependency(betterproto.Message):
    """M003 - 503"""

    dir: str = betterproto.string_field(1)


@dataclass
class GitProgressPullingNewDependency(betterproto.Message):
    """M004 - 504"""

    dir: str = betterproto.string_field(1)


@dataclass
class GitNothingToDo(betterproto.Message):
    """M005 - 505"""

    sha: str = betterproto.string_field(1)


@dataclass
class GitProgressUpdatedCheckoutRange(betterproto.Message):
    """M006 - 506"""

    start_sha: str = betterproto.string_field(1)
    end_sha: str = betterproto.string_field(2)


@dataclass
class GitProgressCheckedOutAt(betterproto.Message):
    """M007 - 507"""

    end_sha: str = betterproto.string_field(1)


@dataclass
class RegistryProgressGETRequest(betterproto.Message):
    """M008 - 508"""

    url: str = betterproto.string_field(1)


@dataclass
class RegistryProgressGETResponse(betterproto.Message):
    """M009 - 509"""

    url: str = betterproto.string_field(1)
    resp_code: int = betterproto.int32_field(2)


@dataclass
class SelectorReportInvalidSelector(betterproto.Message):
    """M010 - 510"""

    valid_selectors: str = betterproto.string_field(1)
    spec_method: str = betterproto.string_field(2)
    raw_spec: str = betterproto.string_field(3)


@dataclass
class JinjaLogInfo(betterproto.Message):
    """M011 - 511"""

    msg: str = betterproto.string_field(1)


@dataclass
class JinjaLogDebug(betterproto.Message):
    """M012 - 512"""

    msg: str = betterproto.string_field(1)


@dataclass
class DepsNoPackagesFound(betterproto.Message):
    """M013 - 513"""

    pass


@dataclass
class DepsStartPackageInstall(betterproto.Message):
    """M014 - 514"""

    package_name: str = betterproto.string_field(1)


@dataclass
class DepsInstallInfo(betterproto.Message):
    """M015 - 515"""

    version_name: str = betterproto.string_field(1)


@dataclass
class DepsUpdateAvailable(betterproto.Message):
    """M016 - 516"""

    version_latest: str = betterproto.string_field(1)


@dataclass
class DepsUpToDate(betterproto.Message):
    """M017 - 517"""

    pass


@dataclass
class DepsListSubdirectory(betterproto.Message):
    """M018 - 518"""

    subdirectory: str = betterproto.string_field(1)


@dataclass
class DepsNotifyUpdatesAvailable(betterproto.Message):
    """M019 - 519"""

    packages: "ListOfStrings" = betterproto.message_field(1)


@dataclass
class RetryExternalCall(betterproto.Message):
    """M020 - 520"""

    attempt: int = betterproto.int32_field(1)
    max: int = betterproto.int32_field(2)


@dataclass
class RecordRetryException(betterproto.Message):
    """M021 - 521"""

    exc: str = betterproto.string_field(1)


@dataclass
class RegistryIndexProgressGETRequest(betterproto.Message):
    """M022 - 522"""

    url: str = betterproto.string_field(1)


@dataclass
class RegistryIndexProgressGETResponse(betterproto.Message):
    """M023 - 523"""

    url: str = betterproto.string_field(1)
    resp_code: int = betterproto.int32_field(2)


@dataclass
class RegistryResponseUnexpectedType(betterproto.Message):
    """M024 - 524"""

    response: str = betterproto.string_field(1)


@dataclass
class RegistryResponseMissingTopKeys(betterproto.Message):
    """M025 - 525"""

    response: str = betterproto.string_field(1)


@dataclass
class RegistryResponseMissingNestedKeys(betterproto.Message):
    """M026 - 526"""

    response: str = betterproto.string_field(1)


@dataclass
class RegistryResponseExtraNestedKeys(betterproto.Message):
    """m027 - 527"""

    response: str = betterproto.string_field(1)


@dataclass
class DepsSetDownloadDirectory(betterproto.Message):
    """M028 - 528"""

    path: str = betterproto.string_field(1)


@dataclass
class DepsUnpinned(betterproto.Message):
    """M029 - 529"""

    revision: str = betterproto.string_field(2)
    git: str = betterproto.string_field(3)


@dataclass
class NoNodesForSelectionCriteria(betterproto.Message):
    """M030 - 530"""

    spec_raw: str = betterproto.string_field(1)


@dataclass
class RunningOperationCaughtError(betterproto.Message):
    """Q001 - 601"""

    exc: str = betterproto.string_field(1)


@dataclass
class CompileComplete(betterproto.Message):
    """Q002 - 602"""

    pass


@dataclass
class FreshnessCheckComplete(betterproto.Message):
    """Q003 - 603"""

    pass


@dataclass
class SeedHeader(betterproto.Message):
    """Q004 - 604"""

    header: str = betterproto.string_field(1)


@dataclass
class SeedHeaderSeparator(betterproto.Message):
    """Q005 - 605"""

    len_header: int = betterproto.int32_field(1)


@dataclass
class SQLRunnerException(betterproto.Message):
    """Q006 - 606"""

    exc: str = betterproto.string_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class LogTestResult(betterproto.Message):
    """Q007 - 607"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)
    num_models: int = betterproto.int32_field(5)
    execution_time: float = betterproto.float_field(6)
    num_failures: int = betterproto.int32_field(7)


@dataclass
class LogStartLine(betterproto.Message):
    """Q011 - 611"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    description: str = betterproto.string_field(2)
    index: int = betterproto.int32_field(3)
    total: int = betterproto.int32_field(4)


@dataclass
class LogModelResult(betterproto.Message):
    """Q012 - 612"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    description: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)
    total: int = betterproto.int32_field(5)
    execution_time: int = betterproto.int32_field(6)


@dataclass
class LogSnapshotResult(betterproto.Message):
    """Q015 - 615"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    description: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)
    total: int = betterproto.int32_field(5)
    execution_time: float = betterproto.float_field(6)
    cfg: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class LogSeedResult(betterproto.Message):
    """Q016 - 616"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    status: str = betterproto.string_field(2)
    result_message: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)
    total: int = betterproto.int32_field(5)
    execution_time: float = betterproto.float_field(6)
    schema: str = betterproto.string_field(7)
    relation: str = betterproto.string_field(8)


@dataclass
class LogFreshnessResult(betterproto.Message):
    """Q018 - 618"""

    status: str = betterproto.string_field(1)
    node_info: "NodeInfo" = betterproto.message_field(2)
    index: int = betterproto.int32_field(3)
    total: int = betterproto.int32_field(4)
    execution_time: float = betterproto.float_field(5)
    source_name: str = betterproto.string_field(6)
    table_name: str = betterproto.string_field(7)


@dataclass
class LogCancelLine(betterproto.Message):
    """Q022 - 622"""

    conn_name: str = betterproto.string_field(1)


@dataclass
class DefaultSelector(betterproto.Message):
    """Q023 - 623"""

    name: str = betterproto.string_field(1)


@dataclass
class NodeStart(betterproto.Message):
    """Q024 - 624"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    unique_id: str = betterproto.string_field(2)


@dataclass
class NodeFinished(betterproto.Message):
    """Q025 - 625"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    unique_id: str = betterproto.string_field(2)
    run_result: "RunResultMsg" = betterproto.message_field(3)


@dataclass
class QueryCancelationUnsupported(betterproto.Message):
    """Q026 - 626"""

    type: str = betterproto.string_field(1)


@dataclass
class ConcurrencyLine(betterproto.Message):
    """Q027 - 627"""

    num_threads: int = betterproto.int32_field(1)
    target_name: str = betterproto.string_field(2)


@dataclass
class CompilingNode(betterproto.Message):
    """Q028 - 628"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class WritingInjectedSQLForNode(betterproto.Message):
    """Q029 - 629"""

    unique_id: str = betterproto.string_field(1)


@dataclass
class NodeCompiling(betterproto.Message):
    """Q030 - 630"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    unique_id: str = betterproto.string_field(2)


@dataclass
class NodeExecuting(betterproto.Message):
    """Q031 - 631"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    unique_id: str = betterproto.string_field(2)


@dataclass
class LogHookStartLine(betterproto.Message):
    """Q032 - 632"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    statement: str = betterproto.string_field(2)
    index: int = betterproto.int32_field(3)
    total: int = betterproto.int32_field(4)


@dataclass
class LogHookEndLine(betterproto.Message):
    """Q033 - 633"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    statement: str = betterproto.string_field(2)
    status: str = betterproto.string_field(3)
    index: int = betterproto.int32_field(4)
    total: int = betterproto.int32_field(5)
    execution_time: float = betterproto.float_field(6)


@dataclass
class SkippingDetails(betterproto.Message):
    """Q034 - 634"""

    node_info: "NodeInfo" = betterproto.message_field(1)
    resource_type: str = betterproto.string_field(2)
    schema: str = betterproto.string_field(3)
    node_name: str = betterproto.string_field(4)
    index: int = betterproto.int32_field(5)
    total: int = betterproto.int32_field(6)


@dataclass
class NothingToDo(betterproto.Message):
    """Q035 - 635"""

    pass


@dataclass
class RunningOperationUncaughtError(betterproto.Message):
    """Q036 - 636"""

    exc: str = betterproto.string_field(2)


@dataclass
class EndRunResult(betterproto.Message):
    """Q037 - 637"""

    results: List["RunResultMsg"] = betterproto.message_field(1)
    elapsed_time: float = betterproto.float_field(2)
    generated_at: datetime = betterproto.message_field(3)
    success: bool = betterproto.bool_field(4)


@dataclass
class NoNodesSelected(betterproto.Message):
    """Q038 - 638"""

    pass


@dataclass
class CatchableExceptionOnRun(betterproto.Message):
    """W002 - 702"""

    exc: str = betterproto.string_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class InternalExceptionOnRun(betterproto.Message):
    """W003 - 703"""

    build_path: str = betterproto.string_field(1)
    exc: str = betterproto.string_field(2)


@dataclass
class GenericExceptionOnRun(betterproto.Message):
    """W004 - 704"""

    build_path: str = betterproto.string_field(1)
    unique_id: str = betterproto.string_field(2)
    exc: str = betterproto.string_field(3)


@dataclass
class NodeConnectionReleaseError(betterproto.Message):
    """W005 - 705"""

    node_name: str = betterproto.string_field(1)
    exc: str = betterproto.string_field(2)
    exc_info: str = betterproto.string_field(3)


@dataclass
class FoundStats(betterproto.Message):
    """W006 - 706"""

    stat_line: str = betterproto.string_field(1)


@dataclass
class MainKeyboardInterrupt(betterproto.Message):
    """Z001 - 801"""

    pass


@dataclass
class MainEncounteredError(betterproto.Message):
    """Z002 - 802"""

    exc: str = betterproto.string_field(1)


@dataclass
class MainStackTrace(betterproto.Message):
    """Z003 - 803"""

    stack_trace: str = betterproto.string_field(1)


@dataclass
class SystemErrorRetrievingModTime(betterproto.Message):
    """Z004 - 804"""

    path: str = betterproto.string_field(1)


@dataclass
class SystemCouldNotWrite(betterproto.Message):
    """Z005 - 805"""

    path: str = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)
    exc: str = betterproto.string_field(3)


@dataclass
class SystemExecutingCmd(betterproto.Message):
    """Z006 - 806"""

    cmd: List[str] = betterproto.string_field(1)


@dataclass
class SystemStdOutMsg(betterproto.Message):
    """Z007 - 807"""

    bmsg: bytes = betterproto.bytes_field(1)


@dataclass
class SystemStdErrMsg(betterproto.Message):
    """Z008 - 808"""

    bmsg: bytes = betterproto.bytes_field(1)


@dataclass
class SystemReportReturnCode(betterproto.Message):
    """Z009 - 809"""

    returncode: int = betterproto.int32_field(1)


@dataclass
class TimingInfoCollected(betterproto.Message):
    """Z010 - 810"""

    pass


@dataclass
class LogDebugStackTrace(betterproto.Message):
    """Z011 - 811"""

    exc_info: str = betterproto.string_field(1)


@dataclass
class CheckCleanPath(betterproto.Message):
    """Z012 - 812"""

    path: str = betterproto.string_field(1)


@dataclass
class ConfirmCleanPath(betterproto.Message):
    """Z013 - 813"""

    path: str = betterproto.string_field(1)


@dataclass
class ProtectedCleanPath(betterproto.Message):
    """Z014 - 814"""

    path: str = betterproto.string_field(1)


@dataclass
class FinishedCleanPaths(betterproto.Message):
    """Z015 - 815"""

    pass


@dataclass
class OpenCommand(betterproto.Message):
    """Z016 - 816"""

    open_cmd: str = betterproto.string_field(1)
    profiles_dir: str = betterproto.string_field(2)


@dataclass
class EmptyLine(betterproto.Message):
    """Z017 - 817"""

    pass


@dataclass
class ServingDocsPort(betterproto.Message):
    """Z018 - 818"""

    address: str = betterproto.string_field(1)
    port: int = betterproto.int32_field(2)


@dataclass
class ServingDocsAccessInfo(betterproto.Message):
    """Z019 - 819"""

    port: str = betterproto.string_field(1)


@dataclass
class ServingDocsExitInfo(betterproto.Message):
    """Z020 - 820"""

    pass


@dataclass
class RunResultWarning(betterproto.Message):
    """Z021 - 821"""

    resource_type: str = betterproto.string_field(1)
    node_name: str = betterproto.string_field(2)
    path: str = betterproto.string_field(3)


@dataclass
class RunResultFailure(betterproto.Message):
    """Z022 - 822"""

    resource_type: str = betterproto.string_field(1)
    node_name: str = betterproto.string_field(2)
    path: str = betterproto.string_field(3)


@dataclass
class StatsLine(betterproto.Message):
    """Z023 - 823"""

    stats: Dict[str, int] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )


@dataclass
class RunResultError(betterproto.Message):
    """Z024 - 824"""

    msg: str = betterproto.string_field(1)


@dataclass
class RunResultErrorNoMessage(betterproto.Message):
    """Z025 - 825"""

    status: str = betterproto.string_field(1)


@dataclass
class SQLCompiledPath(betterproto.Message):
    """Z026 - 826"""

    path: str = betterproto.string_field(1)


@dataclass
class CheckNodeTestFailure(betterproto.Message):
    """Z027 - 827"""

    relation_name: str = betterproto.string_field(1)


@dataclass
class FirstRunResultError(betterproto.Message):
    """Z028 - 828"""

    msg: str = betterproto.string_field(1)


@dataclass
class AfterFirstRunResultError(betterproto.Message):
    """Z029 - 829"""

    msg: str = betterproto.string_field(1)


@dataclass
class EndOfRunSummary(betterproto.Message):
    """Z030 - 830"""

    num_errors: int = betterproto.int32_field(1)
    num_warnings: int = betterproto.int32_field(2)
    keyboard_interrupt: bool = betterproto.bool_field(3)


@dataclass
class LogSkipBecauseError(betterproto.Message):
    """Z034 - 834"""

    schema: str = betterproto.string_field(1)
    relation: str = betterproto.string_field(2)
    index: int = betterproto.int32_field(3)
    total: int = betterproto.int32_field(4)


@dataclass
class EnsureGitInstalled(betterproto.Message):
    """Z036 - 836"""

    pass


@dataclass
class DepsCreatingLocalSymlink(betterproto.Message):
    """Z037 - 837"""

    pass


@dataclass
class DepsSymlinkNotAvailable(betterproto.Message):
    """Z038 - 838"""

    pass


@dataclass
class DisableTracking(betterproto.Message):
    """Z039 - 839"""

    pass


@dataclass
class SendingEvent(betterproto.Message):
    """Z040 - 840"""

    kwargs: str = betterproto.string_field(1)


@dataclass
class SendEventFailure(betterproto.Message):
    """Z041 - 841"""

    pass


@dataclass
class FlushEvents(betterproto.Message):
    """Z042 - 842"""

    pass


@dataclass
class FlushEventsFailure(betterproto.Message):
    """Z043 - 843"""

    pass


@dataclass
class TrackingInitializeFailure(betterproto.Message):
    """Z044 - 844"""

    exc_info: str = betterproto.string_field(1)


@dataclass
class EventBufferFull(betterproto.Message):
    """Z045 - 845"""

    pass


@dataclass
class RunResultWarningMessage(betterproto.Message):
    """Z046 - 846"""

    msg: str = betterproto.string_field(1)


@dataclass
class IntegrationTestInfo(betterproto.Message):
    """T001 - 901"""

    msg: str = betterproto.string_field(1)


@dataclass
class IntegrationTestDebug(betterproto.Message):
    """T002 - 902"""

    msg: str = betterproto.string_field(1)


@dataclass
class IntegrationTestWarn(betterproto.Message):
    """T003 - 903"""

    msg: str = betterproto.string_field(1)


@dataclass
class IntegrationTestError(betterproto.Message):
    """T004 - 904"""

    msg: str = betterproto.string_field(1)


@dataclass
class IntegrationTestException(betterproto.Message):
    """T005 - 905"""

    msg: str = betterproto.string_field(1)


@dataclass
class UnitTestInfo(betterproto.Message):
    """T006 - 906"""

    msg: str = betterproto.string_field(1)
